### ISSUE TITLE
Bring back blog posts (create a MozVR Tumblr?)

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr.com#13]
We removed the blog posts in the recent redesign:

http://web.archive.org/web/20151022204634/http://mozvr.com/posts/webvr-lands-in-nightly/
http://web.archive.org/web/20151022205953/http://mozvr.com/posts/quick-vr-prototypes/

(Per https://www.reddit.com/r/WebVR/comments/3zprl4/how_do_you_guys_mock_up_for_vr/cyolrve)

Some of the old [Projects](http://web.archive.org/web/20151022205348/http://mozvr.com/projects/) [case studies](http://web.archive.org/web/20151022205348/http://mozvr.com/projects/monkeys/) could probably live on some secondary pages too (or in the "Blog" as blog posts). Or Perhaps we could just move our blog to a MozVR Tumblr.

Thoughts, @jcarpenter, @caseyyee?

<hr>

Related to issue #8 (and PR #11)

**Comment by caseyyee** [comment]
Blog posts are definetly useful.   I know that @jcarpenter wanted to re-write/refresh them though.   I think that tumblr or medium would be a better place for the articles themselves to live.  We can link them from the page.

**Comment by caseyyee** [comment]
The project case studies I don't think get much eyeball time and don't think they are worth maintaining IMO.
