### ISSUE TITLE
clicking on a section takes you directly to the top of that section's heading

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr.com#17]
it looks a bit awkward when you click on a nav item and jumps to show the very top of the heading (not with any padding):

![image](https://cloud.githubusercontent.com/assets/203725/12190045/aea84620-b578-11e5-8161-c2b81059fa58.png)

vs.

![image](https://cloud.githubusercontent.com/assets/203725/12190049/b9b06b92-b578-11e5-96dc-aef7993e3bee.png)

this is likely because of the height of the nav bar up top (I think; will have to check)

**Comment by caseyyee** [comment]
Fixed with https://github.com/MozVR/mozvr.com/commit/d166c6159a3956cb47bfafcf398d9fccab740453

**Comment by caseyyee** [comment]
![image](https://cloud.githubusercontent.com/assets/1560884/12192746/46d5e0b6-b596-11e5-9b12-c9759e94334e.png)
![image](https://cloud.githubusercontent.com/assets/1560884/12192760/56c3ace2-b596-11e5-9db1-9821538252d4.png)
