### ISSUE TITLE
Should Sechelt iframe be black until loaded (or show hero placeholder image)?

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr.com#20]
While the iframe is waiting to be loaded, a black (`#333`) background is shown:

![image](https://cloud.githubusercontent.com/assets/203725/12190391/f48d1252-b57c-11e5-8ac7-bcd1a3bb08e4.png)

Perhaps it would be best if we showed the screenshot as a placeholder until then (or maybe not? thoughts, @caseyyee?):

![image](https://cloud.githubusercontent.com/assets/203725/12190400/1470c528-b57d-11e5-9f94-36aa7d52f3cf.png)

**Comment by cvan** [comment]
not going to make a PR because not sure it's any better, but https://github.com/cvan/mozvr.com/tree/show-placeholder-until-iframe-loaded shows how it could be done

**Comment by caseyyee** [comment]
Actually, I think we could just adjust the stylesheet since the background image is already there for mobile.

**Comment by cvan** [comment]
> Actually, I think we could just adjust the stylesheet since the background image is already there for mobile.

yep, I'm just reusing the background image that we show on mobile. though it'd be nice to get a higher-res version for desktop/Retina.
