### ISSUE TITLE
enter vr button on sechelt hero disappears/unaligns when resizing browser

### ISSUE THREAD

**Issue by ngokevin** [MozVR/mozvr.com#5]

**Comment by cvan** [comment]
we're not showing the Enter VR button anymore. right?

**Comment by cvan** [comment]
nevermind, I forgot it's hidden in unsupported browsers. also, it doesn't look like it works for me - regression or never worked?

check http://mozvr.com/demos/sechelt/?sound=false

**Comment by ngokevin** [comment]
This was on the old VR site that had the Hero Sechelt. I think it should be fine now.
