### ISSUE TITLE
Add twitter and facebook card/graph meta

### ISSUE THREAD

**Issue by caseyyee** [MozVR/mozvr.com#7]
as per aframe.io site:
https://github.com/aframevr/aframe-site-dev/blob/master/themes/aframe/layout/layout.ejs#L14-L28

**Comment by cvan** [comment]
it looks like this is all done and looks like the Twitter cards are working:

![image](https://cloud.githubusercontent.com/assets/203725/12190515/37d676ec-b57e-11e5-817a-99104782ec2c.png)

and Facebook cards too:

![image](https://cloud.githubusercontent.com/assets/203725/12190518/4aae2210-b57e-11e5-8a92-0e39a7c3314a.png)

nice!

**Comment by caseyyee** [comment]
Oh yeah, the twitter card looks ugg though.  Will need to fix that.
