### ISSUE TITLE
Request: GLX Stereo Visual as output device on Linux

### ISSUE THREAD

**Issue by stumpelrilz** [MozVR/mozvr.com#70]
I am not completely sure if this is the right place to ask, but hopefully it is ;-)

I would like to use a-frame, that oviously relies on MozVR in the firefox desktop browser,
by using a stereo monitor as output device.

As I meanwhile got to know is that MozVR currently only supports two VR headsets.

So my request ist that MozVR and/or Firefox (on Linux!) should be able to use the GLX stereo visuals that is e.g. provided by NVidia's Quadro graphics cards.

As small example for that could maybe "glxgears" with the parameter "-stereo" serve.

**Comment by caseyyee** [comment]
This is the actual mozvr.com website repo.  A good place for a question like this might be the WebVR mailing list, webvr reddit or slack community.  The links for that are on the community section of the page: http://mozvr.com/#community.
