### ISSUE TITLE
Consider featuring SpaceLamb

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr.com#80]
http://m.spacelamb.12wave.com/

It's quite slick and fun on mobile. Nice graphics.

**Comment by caseyyee** [comment]
Nice.  adding in as mobile demo.

**Comment by caseyyee** [comment]
added in https://github.com/MozVR/mozvr.com/commit/ebda3950d66a597c9df9eeb509e4fb12eb94deaa
